# configuration for https://travis-ci.org/HashEngineering/axej
sudo: false
dist: trusty
language: java
addons:
  hosts:
    - host
  hostname: host
jdk: oraclejdk8
install: true # remove default
script:
  - mvn -q clean install -Pno-network -e -X
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report
